[model]
input_dim = 48
hidden_dim = 128
n_heads = 4
n_layers = 4
num_classes = 1  # Set to 1 for binary classification

[training]
learning_rate = 1e-4
epochs = 200
batch_size = 8
device = "cuda"  # Set to "cuda" for GPU, "cpu" for CPU
